name: ${project.artifactId}
version: '${project.version}'
main: pl.kpgtb.kthirst.KThirst
api-version: 1.14
website: kpgtb.pl
author: KPG_TB
description: Spigot plugin for minecraft 1.14.-1.19. This plugin adds thirst, drinks and machines
depend:
  - KTools
softdepend:
  - PlaceholderAPI

